### ISSUE TITLE
Biome Does Not Automatically Upgrade

### ISSUE THREAD

**Issue by TheDarkula** [biome-sh/biome#13]
I am starting my service with `--strategy at-once --url https://bldr.habitat.sh`, but it seems that biome does not synchronise with the builder instance.

Marking a package as stable/unstable causes no change in the running service.

**Comment by jsirex** [comment]
There is not enough information to understand what's going on.
Once package updated to latest version it stays latest, even if you demote package back.
`--update-condition` option may help you. Also turn on debug logs to see what happens

**Comment by TheDarkula** [comment]
Thank you so much!
Running with `--strategy at-once --url https://bldr.habitat.sh --update-condition latest` made the magic happen :)

**Comment by jsirex** [comment]
It is strange for me. You've used default parameters. Your command is equivalent to simple `--strategy at-once`

**Comment by TheDarkula** [comment]
I did have the thought that I might not have waited long enough for the upgrade to execute.
