### ISSUE TITLE
 How to unload only hart file without using habitat builder

### ISSUE THREAD

**Issue by yryuu** [biome-sh/biome#16]
Hi

I have a request to store the code in the aws environment only.

Therefore
hart file only
I want to deploy by doing "bio svc load" or "bio pkg install", is there any way?

I'm thinking of putting the hart file on aws s3

**Comment by jsirex** [comment]
This is not forum, but a bug tracker.

``` bash
bio pkg install --help            
bio-pkg-install 1.6.544/20220809212946
Installs a Biome package from Builder or locally from a Biome Artifact

USAGE:
    bio pkg install [FLAGS] [OPTIONS] <PKG_IDENT_OR_ARTIFACT>...
```

The package's install accepts hart files directly without builder.
